#!/bin/bash

SCRIPT="$HOME/.config/hypr/scripts/wallpaper-slideshow.sh"
DIR="$1" #TODO: colocar un comprobador de que exista el argumento 1 que es necesario.

notify-send "togle-wallpaper-slideshow.sh"

if pgrep -f "$SCRIPT" > /dev/null; then
    pkill -f "$SCRIPT"
    notify-send "Wallpaper slideshow detenido"
else
    "$SCRIPT" "$DIR" &
    notify-send "Wallpaper slideshow iniciado"
fi